//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.18 at 05:55:47 AM EET 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


// TODO: Auto-generated Javadoc
/**
 * The Class Hosts.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "hosts")
public class Hosts {

    @XmlAttribute(name = "up")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String up;
    @XmlAttribute(name = "down")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String down;
    @XmlAttribute(name = "total", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String total;

    /**
     * Gets the value of the up property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUp() {
        if (up == null) {
            return "0";
        } else {
            return up;
        }
    }

    /**
     * Sets the value of the up property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUp(String value) {
        this.up = value;
    }

    /**
     * Gets the value of the down property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDown() {
        if (down == null) {
            return "0";
        } else {
            return down;
        }
    }

    /**
     * Sets the value of the down property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDown(String value) {
        this.down = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotal(String value) {
        this.total = value;
    }

}
