//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.18 at 05:55:47 AM EET 
//


package jaxb;

import javax.xml.bind.annotation.XmlRegistry;


// TODO: Auto-generated Javadoc
/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nmap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nmap.
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Port }.
     *
     * @return the port
     */
    public Port createPort() {
        return new Port();
    }

    /**
     * Create an instance of {@link State }.
     *
     * @return the state
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link Owner }.
     *
     * @return the owner
     */
    public Owner createOwner() {
        return new Owner();
    }

    /**
     * Create an instance of {@link Service }.
     *
     * @return the service
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Script }.
     *
     * @return the script
     */
    public Script createScript() {
        return new Script();
    }

    /**
     * Create an instance of {@link Smurf }.
     *
     * @return the smurf
     */
    public Smurf createSmurf() {
        return new Smurf();
    }

    /**
     * Create an instance of {@link Postscript }.
     *
     * @return the postscript
     */
    public Postscript createPostscript() {
        return new Postscript();
    }

    /**
     * Create an instance of {@link Nmaprun }.
     *
     * @return the nmaprun
     */
    public Nmaprun createNmaprun() {
        return new Nmaprun();
    }

    /**
     * Create an instance of {@link Scaninfo }.
     *
     * @return the scaninfo
     */
    public Scaninfo createScaninfo() {
        return new Scaninfo();
    }

    /**
     * Create an instance of {@link Verbose }.
     *
     * @return the verbose
     */
    public Verbose createVerbose() {
        return new Verbose();
    }

    /**
     * Create an instance of {@link Debugging }.
     *
     * @return the debugging
     */
    public Debugging createDebugging() {
        return new Debugging();
    }

    /**
     * Create an instance of {@link Target }.
     *
     * @return the target
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Taskbegin }.
     *
     * @return the taskbegin
     */
    public Taskbegin createTaskbegin() {
        return new Taskbegin();
    }

    /**
     * Create an instance of {@link Taskprogress }.
     *
     * @return the taskprogress
     */
    public Taskprogress createTaskprogress() {
        return new Taskprogress();
    }

    /**
     * Create an instance of {@link Taskend }.
     *
     * @return the taskend
     */
    public Taskend createTaskend() {
        return new Taskend();
    }

    /**
     * Create an instance of {@link Prescript }.
     *
     * @return the prescript
     */
    public Prescript createPrescript() {
        return new Prescript();
    }

    /**
     * Create an instance of {@link Host }.
     *
     * @return the host
     */
    public Host createHost() {
        return new Host();
    }

    /**
     * Create an instance of {@link Output }.
     *
     * @return the output
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link Runstats }.
     *
     * @return the runstats
     */
    public Runstats createRunstats() {
        return new Runstats();
    }

    /**
     * Create an instance of {@link Osfingerprint }.
     *
     * @return the osfingerprint
     */
    public Osfingerprint createOsfingerprint() {
        return new Osfingerprint();
    }

    /**
     * Create an instance of {@link Extrareasons }.
     *
     * @return the extrareasons
     */
    public Extrareasons createExtrareasons() {
        return new Extrareasons();
    }

    /**
     * Create an instance of {@link Distance }.
     *
     * @return the distance
     */
    public Distance createDistance() {
        return new Distance();
    }

    /**
     * Create an instance of {@link Times }.
     *
     * @return the times
     */
    public Times createTimes() {
        return new Times();
    }

    /**
     * Create an instance of {@link Tcpsequence }.
     *
     * @return the tcpsequence
     */
    public Tcpsequence createTcpsequence() {
        return new Tcpsequence();
    }

    /**
     * Create an instance of {@link Hosts }.
     *
     * @return the hosts
     */
    public Hosts createHosts() {
        return new Hosts();
    }

    /**
     * Create an instance of {@link Hostnames }.
     *
     * @return the hostnames
     */
    public Hostnames createHostnames() {
        return new Hostnames();
    }

    /**
     * Create an instance of {@link Hostname }.
     *
     * @return the hostname
     */
    public Hostname createHostname() {
        return new Hostname();
    }

    /**
     * Create an instance of {@link Cpe }.
     *
     * @return the cpe
     */
    public Cpe createCpe() {
        return new Cpe();
    }

    /**
     * Create an instance of {@link Finished }.
     *
     * @return the finished
     */
    public Finished createFinished() {
        return new Finished();
    }

    /**
     * Create an instance of {@link Os }.
     *
     * @return the os
     */
    public Os createOs() {
        return new Os();
    }

    /**
     * Create an instance of {@link Portused }.
     *
     * @return the portused
     */
    public Portused createPortused() {
        return new Portused();
    }

    /**
     * Create an instance of {@link Osmatch }.
     *
     * @return the osmatch
     */
    public Osmatch createOsmatch() {
        return new Osmatch();
    }

    /**
     * Create an instance of {@link Status }.
     *
     * @return the status
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Address }.
     *
     * @return the address
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Ports }.
     *
     * @return the ports
     */
    public Ports createPorts() {
        return new Ports();
    }

    /**
     * Create an instance of {@link Uptime }.
     *
     * @return the uptime
     */
    public Uptime createUptime() {
        return new Uptime();
    }

    /**
     * Create an instance of {@link Ipidsequence }.
     *
     * @return the ipidsequence
     */
    public Ipidsequence createIpidsequence() {
        return new Ipidsequence();
    }

    /**
     * Create an instance of {@link Tcptssequence }.
     *
     * @return the tcptssequence
     */
    public Tcptssequence createTcptssequence() {
        return new Tcptssequence();
    }

    /**
     * Create an instance of {@link Hostscript }.
     *
     * @return the hostscript
     */
    public Hostscript createHostscript() {
        return new Hostscript();
    }

    /**
     * Create an instance of {@link Trace }.
     *
     * @return the trace
     */
    public Trace createTrace() {
        return new Trace();
    }

    /**
     * Create an instance of {@link Hop }.
     *
     * @return the hop
     */
    public Hop createHop() {
        return new Hop();
    }

    /**
     * Create an instance of {@link Osclass }.
     *
     * @return the osclass
     */
    public Osclass createOsclass() {
        return new Osclass();
    }

    /**
     * Create an instance of {@link Table }.
     *
     * @return the table
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Elem }.
     *
     * @return the elem
     */
    public Elem createElem() {
        return new Elem();
    }

    /**
     * Create an instance of {@link Extraports }.
     *
     * @return the extraports
     */
    public Extraports createExtraports() {
        return new Extraports();
    }

}
