//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.18 at 05:55:47 AM EET 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


// TODO: Auto-generated Javadoc
/**
 * The Class State.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "state")
public class State {

    @XmlAttribute(name = "state", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String state;
    @XmlAttribute(name = "reason", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String reason;
    @XmlAttribute(name = "reason_ttl", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String reasonTtl;
    @XmlAttribute(name = "reason_ip")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String reasonIp;

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the reasonTtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonTtl() {
        return reasonTtl;
    }

    /**
     * Sets the value of the reasonTtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonTtl(String value) {
        this.reasonTtl = value;
    }

    /**
     * Gets the value of the reasonIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonIp() {
        return reasonIp;
    }

    /**
     * Sets the value of the reasonIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonIp(String value) {
        this.reasonIp = value;
    }

}
