//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.18 at 05:55:47 AM EET 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


// TODO: Auto-generated Javadoc
/**
 * The Class Times.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "times")
public class Times {

    @XmlAttribute(name = "srtt", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String srtt;
    @XmlAttribute(name = "rttvar", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rttvar;
    @XmlAttribute(name = "to", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String to;

    /**
     * Gets the value of the srtt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrtt() {
        return srtt;
    }

    /**
     * Sets the value of the srtt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrtt(String value) {
        this.srtt = value;
    }

    /**
     * Gets the value of the rttvar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRttvar() {
        return rttvar;
    }

    /**
     * Sets the value of the rttvar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRttvar(String value) {
        this.rttvar = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTo(String value) {
        this.to = value;
    }

}
